### ISSUE TITLE
Slajdy z FF 2019

### ISSUE THREAD

**Issue by vilemmarsik** [soulcharmer/FF_slides#1]
Můžu poprosit slíbené slajdy z přednášky o školství?
Díky..

**Comment by soulcharmer** [comment]
Jasne, ted jsem uploadnul zero waste, ten chtelo vic lidi, ty o vzdelani nahraju jako dalsi v rade.

**Comment by soulcharmer** [comment]
konecne hotovo:

https://github.com/soulcharmer/FF_slides/blob/master/education.odp

feedback welcome :)
